name: fstore
publish_to: "none"
description: Mobile commerce app by Flutter

# The following defines the version and build number for yourr application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.10.2+3022

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  inspireui: 1.0.15

  # Base
  intl: 0.17.0
  crypto: 3.0.1
  path_provider: 2.0.9
  url_launcher: 6.0.20
  localstorage: 4.0.0+1
  http: 0.13.4
  http_auth: 1.0.1
  share: 2.0.4
  #  wakelock: 0.5.6

  # Internet Connectivity
  internet_connection_checker: ^0.0.1+3
  connectivity_plus: ^2.3.5
  # Modal BottomSheet
  modal_bottom_sheet: ^2.0.1


  # FIREBASE PACKAGES
  firebase_core: 1.12.0
  firebase_analytics: 8.3.3
  firebase_auth: 3.3.7
  firebase_remote_config: 2.0.0
  firebase_dynamic_links: 4.0.6
  cloud_firestore: 3.1.8

  # STATE MANAGEMENT
  provider: 6.0.2
  get_it: 7.2.0

  # SPLASH SCREEN, ONBOARD
  flare_loading: 3.0.0
  rive: 0.8.1

  # ICON FONTS
  cupertino_icons: 1.0.4

  # WEB TOOLS
  html_unescape: 2.0.0
  webview_flutter: 3.0.0
  webview_flutter_web: 0.1.0+1
  responsive_builder: 0.4.2
  flutter_inappwebview: 5.3.2

  # HTML render
  flutter_widget_from_html_core: 0.8.5+1
  fwfh_webview: 0.6.2+2
  fwfh_svg: 0.7.2
  fwfh_cached_network_image: 0.7.0+2
  fwfh_url_launcher: 0.6.1+3
  fwfh_chewie: 0.7.0+1

  # MAP
  google_maps_flutter: 2.1.1
  location: 4.3.0
  maps_launcher: 2.0.1
  geocode: 1.0.1

  # AUTHENTICATION
  the_apple_sign_in: 1.1.1
  flutter_facebook_auth: 4.1.0
  google_sign_in: 5.4.0
  sms_autofill: 2.2.0

  # PUSH NOTIFICATION
  firebase_messaging: 11.2.6
  notification_permissions: 0.6.1
  flutter_local_notifications: 9.3.2
  onesignal_flutter: 3.2.8

  # FILES, IMAGES
  file_picker: 4.4.0
  cached_network_image: 3.2.0
  image: 3.1.3
  transparent_image: 2.0.0
  image_picker: 0.8.4+9
  flutter_native_image: 0.0.6+1
  multi_image_picker2: 5.0.2
  flutter_cache_manager: 3.3.0

  # ADS
  google_mobile_ads: 1.1.0

  # TOOLS
  google_fonts: 2.3.1
  random_string: 2.3.1
  json_annotation: 4.4.0
  timeago: 3.2.2
  universal_platform: 1.0.0+1
  uuid: 3.0.5
  easy_debounce: 2.0.2+1
  devicelocale: 0.5.0
  collection: 1.15.0
  visibility_detector: 0.2.2
  rate_my_app: 1.1.2
  flutter_linkify: 5.0.2
  gms_check: 1.0.0
  email_validator: 2.0.1

  # UI
  flutter_spinkit: 5.1.0
  smooth_page_indicator: 1.0.0+2
  animated_text_kit: 4.2.1
  animations: 2.0.2
  flash: 2.0.3+2
  flutter_staggered_grid_view: 0.6.1
  flutter_swiper_null_safety: 1.0.2
  pull_to_refresh: 2.0.0
  implicitly_animated_reorderable_list: 0.4.2
  rubber: ^1.0.1
  pin_code_fields: 7.3.0
  country_code_picker: 2.0.2
  country_pickers: 2.0.0
  intro_slider: 3.0.3
  dropdown_search: 2.0.1
  flutter_calendar_carousel: 2.1.0
  currency_text_input_formatter: 2.1.5
  flutter_zoom_drawer: 2.3.1
  qr_code_scanner: 0.7.0
  paytm_allinonesdk: 1.1.5
  charts_flutter: 0.12.0
  extended_image: 6.0.1
  dotted_decoration: 2.0.0
  flex_color_scheme: ^4.2.0
  lottie: 1.2.2
  razorpay_flutter: 1.2.9
  flutter_native_splash: 2.0.4
  geolocator: ^7.7.1
  geocoding: ^2.0.2
  places_service: ^0.1.0+2
  fluttertoast:
  flutter_google_places: ^0.3.0
  geocoder2: ^1.1.0






  #### For Shopify GraphQL
  graphql: 5.0.0
  awesome_card: 1.1.7

  ###---- Some extra feature is disable by default -----###
  ### â–¶ï¸ Audio Feature
  ### Search "Enable Audio feature" & uncomment to use - https://tppr.me/Z1TX5
#  audio_manager: ^0.8.2
  ### ðŸ’³ Facebook Ads
  ### Search "Enable Facebook Ads" & uncomment to use  - https://tppr.me/9Pkf9
  # facebook_audience_network: 1.0.0-nullsafety.0

dev_dependencies:
  flutter_launcher_icons: 0.9.2
  flutter_lints: 1.0.4

#  convert_data:
#    path: _dev/convert_data

## Enable to use Flutter Test Driver
#  flutter_driver:
#    sdk: flutter
#  test: 1.16.5
#  dependency_validator: ^3.1.2  # pub run dependency_validator

## Enable To run json serializer, run:
## flutter pub run build_runner build --build-filter="lib/models/serializers/*.dart" --delete-conflicting-outputs
## flutter pub run build_runner serve --build-filter="lib/models/serializers/*.dart"
#  build_runner: 2.0.3
#  json_serializable: 4.1.2

#  Run this script to generate the app icon: flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - lib/config/
    - lib/config/mocks/
    - lib/config/states/
    - lib/config/stories/
    - assets/icons/credit_cards/
    - assets/icons/tabs/
    - assets/icons/payment/
    - assets/icons/logins/
    - assets/images/
    - assets/images/country/
    - assets/images/favicon/
    - assets/html/
    - google_fonts/
    - assets/tab/
    - assets/

flutter_intl:
  enabled: true
  use_deferred_loading: true
